package buscaminas;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import buscaminas.Cuadro;
import java.awt.Color;
import java.nio.file.Paths;
import java.util.Arrays;
import javax.swing.ImageIcon;

public class Finestra extends javax.swing.JFrame implements ActionListener {
    
    int numerofiles = 0;
    int numerocols = 0;
    int contadorMines = 0;
    int numeroCuadros = 0;
    int contadorTrobats = 0;
    Cuadro[][] cuadro = null;
    ImageIcon[] arrayNumeros = new ImageIcon[8];

    //Dubte on posar-ho
    int[][] direccions = {{0, 1}, {0, -1}, {1, 0}, {-1, 0}, {1, 1}, {1, -1}, {-1, 1}, {-1, -1}};
    
    String currentPath = Paths.get("").toAbsolutePath().toString();
    
    public Finestra() {
        System.out.println(currentPath);
        initComponents();
    }

    //Accions, click als botons
    public void actionPerformed(ActionEvent e) {
        clickBoto(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        files = new javax.swing.JTextField();
        cols = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pantalla_joc = new javax.swing.JPanel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jLabel1.setText("Files:");
        
        jLabel2.setText("Columnes");
        
        files.setText("1000");
        
        cols.setText("1000");
        
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(files, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                                                .addComponent(jButton1)
                                                .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(files, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(cols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1)))
                                .addContainerGap(40, Short.MAX_VALUE))
        );
        
        javax.swing.GroupLayout pantalla_jocLayout = new javax.swing.GroupLayout(pantalla_joc);
        pantalla_joc.setLayout(pantalla_jocLayout);
        pantalla_jocLayout.setHorizontalGroup(
                pantalla_jocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        pantalla_jocLayout.setVerticalGroup(
                pantalla_jocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 314, Short.MAX_VALUE)
        );
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pantalla_joc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pantalla_joc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iniciar();
        this.paintAll(this.getGraphics());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    //Metode inici
    private void iniciar() {
        this.pantalla_joc.removeAll();//Borrar tot el tauler
        int nFiles, nCol;
        nFiles = Integer.parseInt(this.files.getText());
        nCol = Integer.parseInt(this.cols.getText());
        numerofiles = nFiles;
        numerocols = nCol;
        boolean flag = false;
        
        arrayNumeros[0] = new ImageIcon(currentPath + "/src/images/1.png");
        arrayNumeros[1] = new ImageIcon(currentPath + "/src/images/2.png");
        arrayNumeros[2] = new ImageIcon(currentPath + "/src/images/3.png");
        arrayNumeros[3] = new ImageIcon(currentPath + "/src/images/4.png");
        arrayNumeros[4] = new ImageIcon(currentPath + "/src/images/5.png");
        arrayNumeros[5] = new ImageIcon(currentPath + "/src/images/6.png");
        arrayNumeros[6] = new ImageIcon(currentPath + "/src/images/7.png");
        arrayNumeros[7] = new ImageIcon(currentPath + "/src/images/8.png");
        //Crear els botons de la la interficie
        this.pantalla_joc.setLayout(new java.awt.GridLayout(nFiles, nCol));
        this.numeroCuadros = nFiles * nCol;
        this.contadorMines = 0;
        
        int minim = (int) ((nFiles * nCol) * 0.1);
        
        Cuadro[][] arraycuadro = new Cuadro[nFiles][nCol];
        //Creador dels objectes botons
        for (int f = 0; f < nFiles; f++) {
            for (int c = 0; c < nCol; c++) {
                
                Cuadro cuadrotemp = new Cuadro();
                cuadrotemp.setPos(f, c);
                arraycuadro[f][c] = cuadrotemp;
                cuadrotemp.addActionListener(this);
                if (cuadrotemp.estatMinat()) {
                    contadorMines++;
                }
                while (c == nCol - 1) {
                    flag = true;
                    break;
                }
                
                cuadrotemp.setVisible(true);
                this.pantalla_joc.add(cuadrotemp);
            }
        }
        cuadro = arraycuadro;
        //Comprovar el minim de mines

        if (contadorMines < minim) {
            int bombesAsignar = minim - contadorMines;
            for (int i = 0; i < bombesAsignar; i++) {
                int calcFiles = (int) (Math.random() * nFiles);
                int calcCol = (int) (Math.random() * nCol);
                if (!arraycuadro[calcFiles][calcCol].estatMinat()) {
                    arraycuadro[calcFiles][calcCol].setMina(true);
                }
            }
        }
//Comprovar el voltant
        for (int f = 0; f < nFiles; f++) {
            for (int c = 0; c < nCol; c++) {
                int contadorBombesDevora = 0;
                for (int i = 0; i < direccions.length; i++) {
                    if (comprovarDireccions(arraycuadro, direccions[i], nFiles, nCol, f, c)) {
                        contadorBombesDevora++;
                    }
                }
                arraycuadro[f][c].setMinesProximes(contadorBombesDevora);
            }
            
        }
    }
    
    private static boolean comprovarDireccions(Cuadro[][] posCuadro, int[] dirs, int nFiles, int nCol, int fAct, int cAct) {
        int dfila = (fAct + dirs[0]);
        int dcolumn = (cAct + dirs[1]);
        boolean avançar = ((dfila >= 0) && (dfila < nFiles)) && ((dcolumn >= 0) && (dcolumn < nCol));
        boolean bomba = false;
        
        if (avançar) {
            if (posCuadro[dfila][dcolumn].estatMinat()) {
                bomba = true;
            }
        }
        
        return bomba;
    }
    
    private boolean comprovarDireccio(int[] dirs, int f, int c) {
        int dfila = (f + dirs[0]);
        int dcolumn = (c + dirs[1]);
        boolean avançar = ((dfila >= 0) && (dfila < numerofiles)) && ((dcolumn >= 0) && (dcolumn < numerocols));
        
        if (avançar) {
            if (cuadro[dfila][dcolumn].getMinesProximes() == 0) {
                cuadro[dfila][dcolumn].setBackground(Color.GREEN);
                for (int fa = 0; fa < direccions[0].length; fa++) {
                    Cuadro cuadrotemp2 = cuadro[dfila + direccions[fa][0]][dcolumn + direccions[fa][1]];
                    int width = cuadrotemp2.getWidth()/2;
                    int height = cuadrotemp2.getHeight()/2;
                    int mprox = cuadrotemp2.getMinesProximes();
                    if(mprox!=0){
                        ImageIcon numeroEscalat = new ImageIcon(arrayNumeros[mprox - 1].getImage().getScaledInstance(width, height, java.awt.Image.SCALE_DEFAULT));
                        cuadrotemp2.setBackground(Color.GREEN);
                        cuadrotemp2.setIcon(numeroEscalat);
                    } else {
                        cuadrotemp2.setBackground(Color.GREEN);
                    }
                    
                }
            } 
        }
        return true;
    }
//Fi de comprovar el voltant

    private void clickBoto(ActionEvent e) {
        Cuadro cuadrotemp2 = (Cuadro) e.getSource();
        int width = cuadrotemp2.getWidth() / 2;
        int height = cuadrotemp2.getHeight() / 2;
        
        ImageIcon image = new ImageIcon(currentPath + "/src/images/mina.png");
        ImageIcon imageEscalada = new ImageIcon(image.getImage().getScaledInstance(width, height, java.awt.Image.SCALE_DEFAULT));
        //Comprovador si esta minat
        if (cuadrotemp2.estatMinat()) {
            for (int f = 0; f < cuadro.length; f++) {
                for (int c = 0; c < cuadro.length; c++) {
                    if (cuadro[f][c].estatMinat()) {
                        cuadro[f][c].setIcon(imageEscalada);
                        cuadro[f][c].setBackground(Color.red);
                    }
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, "BUM! Has perdut.");
            this.contadorTrobats = 0;
            this.pantalla_joc.removeAll();
        } else {
            if (cuadrotemp2.getMinesProximes() != 0) {
                ImageIcon numeroEscalat = new ImageIcon(arrayNumeros[(cuadrotemp2.getMinesProximes()) - 1].getImage().getScaledInstance(width, height, java.awt.Image.SCALE_DEFAULT));
                cuadrotemp2.setBackground(Color.GREEN);
                cuadrotemp2.setIcon(numeroEscalat);
            } else {
                cuadrotemp2.setBackground(Color.GREEN);
            }
            contadorTrobats++;
            int a = 1;
            int expfila = cuadrotemp2.getFila();
            int expcolumna = cuadrotemp2.getColumna();
            firstloop:
            for (int i = 0; i < a; i++) {
                a++;
                for (int d = 0; d < direccions.length; d++) {
                    if (!comprovarDireccio(direccions[d], expfila, expcolumna)) {
                        break firstloop;
                    }
                }
            }
            
            if ((numeroCuadros - contadorMines) == contadorTrobats) {
                javax.swing.JOptionPane.showMessageDialog(this, "GG!");
                this.pantalla_joc.removeAll();
            }
        }
    }
    //EXPERIMENTS

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cols;
    private javax.swing.JTextField files;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pantalla_joc;
    // End of variables declaration//GEN-END:variables
}
